### ISSUE TITLE
REPL loop throws a PlatformNotSupportedException on Unix platforms.

### ISSUE THREAD

**Issue by joelday** [reubeno/NClap#19]
This is with 2.0.0-beta2. ConsolePal doesn't support get_CursorVisible() on Unix. (See https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L289)

```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.get_CursorVisible()
   at NClap.ConsoleInput.ConsoleReader.ReadLine()
...
```

**Comment by joelday** [comment]
set_CursorSize() is not supported either.

**Comment by reubeno** [comment]
Good catch!  We haven't done extensive testing of the REPL support on non-Windows platforms.  I've since run all of the existing unit tests on both Windows and Ubuntu, and found a small handful of issues.  (There were plenty of problems in the tests themselves too.)

I'll submit a new PR shortly with proposed fixes to address them.  I'm not happy with the resolution for some of the issues, but would recommend that we move ahead with them for now--to get to passing tests.  We can then come back and improve later.

**Comment by reubeno** [comment]
Okay, the PR has been completed into 'master' with fixes for these two issues (and a handful more).  We'll try to get an updated beta NuGet package posted within the next day or two.  In the meantime, please do let us know if you see any other problems on non-Windows platforms...  (Feel free to reactivate this issue if you don't see this being resolved for you.)

**Comment by reubeno** [comment]
I've just posted v2.0.0-beta3 to nuget.org.  It might take some time to index, but it should include this PR and a few others.  Feedback welcome!

**Comment by joelday** [comment]
@reubeno Thanks a ton! Works great.
