### ISSUE TITLE
Changing Prompt string in runtime with ColoredString, take the string but no color

### ISSUE THREAD

**Issue by javierbarre** [reubeno/NClap#67]
I want to show some session info in the prompt string (such as git bash for example).
Depending on a session state, I need to change the Prompt string.

int status=1;
_myLoopClient.Prompt = new NClap.Utilities.ColoredString($"stat({status})$ ", ConsoleColor.Blue);

The prompt change successfully but the COLOR does not refresh to the selected one. It remains in the default color.

**Comment by reubeno** [comment]
I see the problem; the `ILoopClient` interface (and the `ConsoleLoopClient` implementation) expose `Prompt` as a plain `string` property.  When we plumbed through more support for string color, this property must not have gotten updated.  It also looks like there's a gap in the unit tests; we're not validating that changes to the loop client's prompt are picked up by a loop that is executing.  Sounds like that's not the problem here, though.

Although I don't think the impact would be high, changing the type of this property would be a breaking change to the API.  My thought is we can add an additional property on `ILoopClient` for the time-being (e.g. `ColoredString? PromptWithColor { get; set; }`) and if/when we rev the major version of NClap at some point in the future, we can coalesce them.  The only potential confusion is that this isn't terribly discoverable; because a `ColoredString` implicitly coerces to a `string`, you'd need to know to use the alternate property :-/.

@javierbarre , do you think the above proposal would work for you?

**Comment by javierbarre** [comment]
Yes, adding a new property on `ILoopClient` will work perfectly for me. Thanks!!

**Comment by reubeno** [comment]
The addition is now in `master`, and I've released v2.3.5 with it.  Package has been posted to nuget.org; it should show up in the nuget.org index soon.

**Comment by javierbarre** [comment]
It worked great, Thanks!
